<?php

namespace DirectoryTree\Dummy;

use BadMethodCallException;
use Closure;
use Faker\Factory as FakerFactory;
use Faker\Generator;
use Illuminate\Container\Container;
use Illuminate\Database\Eloquent\Factories\Factory as EloquentFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Collection;
use Illuminate\Support\Traits\Conditionable;
use Illuminate\Support\Traits\Macroable;

/**
 * @template TClass of object
 */
class Factory
{
    use Conditionable;
    use Macroable {
        __call as macroCall;
    }

    /**
     * The current Faker instance.
     */
    protected Generator $faker;

    /**
     * Constructor.
     */
    public function __construct(
        protected ?int $count = null,
        protected ?string $class = null,
        /** @var (Closure(Generator, array<string, mixed>): TClass)|null */
        protected ?Closure $using = null,
        /** @var Collection<int, callable(array<string, mixed>): array<string, mixed>> */
        protected Collection $states = new Collection,
        /** @var Collection<int, Closure(TClass): mixed> */
        protected Collection $afterMaking = new Collection,
    ) {
        $this->faker = $this->newFaker();
    }

    /**
     * Get a new dummy factory instance for the given attributes.
     *
     * @param  callable(array<string, mixed>): array<string, mixed>|array<string, mixed>  $attributes
     */
    public static function new(callable|array $attributes = []): static
    {
        return (new static)->state($attributes)->configure();
    }

    /**
     * Get a new dummy factory instance for the given number of classes.
     */
    public static function times(int $count): static
    {
        return static::new()->count($count);
    }

    /**
     * Define the dummy class' default state.
     *
     * @return array<string, mixed>
     */
    protected function definition(): array
    {
        return [];
    }

    /**
     * Generate a new dummy class instance.
     *
     * @param  array<string, mixed>  $attributes
     * @return TClass
     */
    protected function generate(array $attributes): mixed
    {
        return new Data($attributes);
    }

    /**
     * Configure the dummy factory.
     */
    protected function configure(): static
    {
        return $this;
    }

    /**
     * Create a new collection of dummy instances.
     *
     * @param  array<int, TClass>  $instances
     * @return Collection<int, TClass>|mixed
     */
    protected function collect(array $instances = []): mixed
    {
        return new Collection($instances);
    }

    /**
     * Get the raw attributes generated by the factory.
     *
     * @param  callable(array<string, mixed>): array<string, mixed>|array<string, mixed>  $attributes
     * @return array<string, mixed>|array<int, array<string, mixed>>
     */
    public function raw(callable|array $attributes = []): array
    {
        if ($this->count === null) {
            return $this->state($attributes)->getExpandedAttributes();
        }

        return array_map(function () use ($attributes) {
            return $this->state($attributes)->getExpandedAttributes();
        }, range(1, $this->count));
    }

    /**
     * Create a collection of classes.
     *
     * @param  callable(array<string, mixed>): array<string, mixed>|array<string, mixed>  $attributes
     * @return TClass|Collection<int, TClass>|mixed
     */
    public function make(callable|array $attributes = []): mixed
    {
        if (! empty($attributes)) {
            return $this->state($attributes)->make();
        }

        if ($this->count === null) {
            return tap($this->makeInstance(), function ($instance) {
                $this->callAfterMaking($this->collect([$instance]));
            });
        }

        if ($this->count < 1) {
            return $this->collect();
        }

        $instances = $this->collect(array_map(function () {
            return $this->makeInstance();
        }, range(1, $this->count)));

        $this->callAfterMaking($instances);

        return $instances;
    }

    /**
     * Make a single instance of the class.
     *
     * @param  callable(array<string, mixed>): array<string, mixed>|array<string, mixed>  $attributes
     * @return TClass
     */
    public function makeOne(callable|array $attributes = []): mixed
    {
        return $this->count(null)->make($attributes);
    }

    /**
     * Create a collection of classes.
     *
     * @param  iterable<int, callable(array<string, mixed>): array<string, mixed>|array<string, mixed>>|int|null  $records
     * @return Collection<int, TClass>|mixed
     */
    public function makeMany(iterable|int|null $records = null): mixed
    {
        $records ??= ($this->count ?? 1);

        $this->count = null;

        if (is_numeric($records)) {
            $records = array_fill(0, $records, []);
        }

        return $this->collect(
            (new Collection($records))->map(function ($record) {
                return $this->state($record)->make();
            })->all()
        );
    }

    /**
     * Create a callback that makes the class when invoked.
     *
     * @param  array<string, mixed>  $attributes
     * @return Closure(): (TClass|Collection<int, TClass>|mixed)
     */
    public function lazy(array $attributes = []): Closure
    {
        return fn () => $this->make($attributes);
    }

    /**
     * Make an instance of the class with the given attributes.
     *
     * @return TClass
     */
    protected function makeInstance(): mixed
    {
        $attributes = $this->getExpandedAttributes();

        if ($this->using) {
            return ($this->using)($this->faker, $attributes);
        }

        return $this->generate($attributes);
    }

    /**
     * Get a raw attributes array for the class.
     *
     * @return array<string, mixed>
     */
    protected function getExpandedAttributes(): array
    {
        return $this->expandAttributes($this->getRawAttributes());
    }

    /**
     * Get the raw attributes for the class as an array.
     *
     * @return array<string, mixed>
     */
    protected function getRawAttributes(): array
    {
        return $this->states->pipe(function ($states) {
            return $states;
        })->reduce(function ($carry, $state) {
            if ($state instanceof Closure) {
                $state = $state->bindTo($this);
            }

            return array_merge($carry, $state($carry));
        }, $this->definition());
    }

    /**
     * Expand all attributes to their underlying values.
     *
     * @param  array<string, mixed>  $definition
     * @return array<string, mixed>
     */
    protected function expandAttributes(array $definition): array
    {
        return (new Collection($definition))->map(function ($attribute, $key = null) use (&$definition) {
            $attribute = $this->expandAttribute($attribute, $definition);

            $definition[$key] = $attribute;

            return $attribute;
        })->all();
    }

    /**
     * Expand the given attribute to its underlying value.
     *
     * @param  array<string, mixed>  $definition
     */
    protected function expandAttribute(mixed $attribute, array $definition): mixed
    {
        $attribute = $this->expandAttributeValue($attribute);

        // Callables can be strings or array definitions, so we will only call
        // those attributes that are intended to be evaluated by the factory.
        if (is_callable($attribute) && ! is_string($attribute) && ! is_array($attribute)) {
            $attribute = $attribute($definition);
        }

        return $this->expandAttributeValue($attribute);
    }

    /**
     * Expand non-callable attribute values to their underlying value.
     */
    protected function expandAttributeValue(mixed $attribute): mixed
    {
        if ($attribute instanceof EloquentFactory) {
            return $attribute->create()->getKey();
        }

        if ($attribute instanceof Model) {
            return $attribute->getKey();
        }

        return $attribute;
    }

    /**
     * Add a new state transformation to the class definition.
     *
     * @param  callable(array<string, mixed>): array<string, mixed>|array<string, mixed>  $state
     */
    public function state(callable|array $state): static
    {
        return $this->newInstance([
            'states' => $this->states->concat([
                is_callable($state) ? $state : fn () => $state,
            ]),
        ]);
    }

    /**
     * Prepend a new state transformation to the class definition.
     *
     * @param  callable(array<string, mixed>): array<string, mixed>|array<string, mixed>  $state
     */
    public function prependState(callable|array $state): static
    {
        return $this->newInstance([
            'states' => $this->states->prepend(
                is_callable($state) ? $state : fn () => $state,
            ),
        ]);
    }

    /**
     * Set a single class attribute.
     */
    public function set(string|int $key, mixed $value): static
    {
        return $this->state([$key => $value]);
    }

    /**
     * Add a new sequenced state transformation to the class definition.
     */
    public function sequence(mixed ...$sequence): static
    {
        return $this->state(new Sequence(...$sequence));
    }

    /**
     * Add a new sequenced state transformation to the class definition and update the pending creation count to the size of the sequence.
     */
    public function forEachSequence(array ...$sequence): static
    {
        return $this->state(new Sequence(...$sequence))->count(count($sequence));
    }

    /**
     * Add a new cross joined sequenced state transformation to the class definition.
     */
    public function crossJoinSequence(array ...$sequence): static
    {
        return $this->state(new CrossJoinSequence(...$sequence));
    }

    /**
     * Set the callback to be used to create the class instance.
     *
     * @param  Closure(Generator, array<string, mixed>): TClass  $callback
     */
    public function using(Closure $callback): static
    {
        return $this->newInstance([
            'using' => $callback,
        ]);
    }

    /**
     * Add a new "after making" callback to the class definition.
     *
     * @param  Closure(TClass): mixed  $callback
     */
    public function afterMaking(Closure $callback): static
    {
        return $this->newInstance([
            'afterMaking' => $this->afterMaking->concat([$callback]),
        ]);
    }

    /**
     * Remove the "after making" callbacks from the factory.
     */
    public function withoutAfterMaking(): static
    {
        return $this->newInstance([
            'afterMaking' => new Collection,
        ]);
    }

    /**
     * Call the "after making" callbacks for the given class instances.
     *
     * @param  iterable<int, TClass>  $instances
     */
    protected function callAfterMaking(iterable $instances): void
    {
        foreach ($instances as $instance) {
            $this->afterMaking->each(
                fn ($callback) => $callback($instance)
            );
        }
    }

    /**
     * Specify how many dummy classes should be generated.
     */
    public function count(?int $count): static
    {
        return $this->newInstance(['count' => $count]);
    }

    /**
     * Create a new instance of the factory builder with the given mutated properties.
     *
     * @param  array<string, mixed>  $arguments
     */
    protected function newInstance(array $arguments = []): static
    {
        return new static(...array_values(array_merge([
            'count' => $this->count,
            'class' => $this->class,
            'using' => $this->using,
            'states' => $this->states,
            'afterMaking' => $this->afterMaking,
        ], $arguments)));
    }

    /**
     * Get the Faker instance.
     */
    public function faker(): Generator
    {
        return $this->faker ??= $this->newFaker();
    }

    /**
     * Get a new Faker instance.
     */
    protected function newFaker(): Generator
    {
        if (class_exists(Container::class)) {
            return Container::getInstance()->make(Generator::class);
        }

        return FakerFactory::create();
    }

    /**
     * Handle dynamic state method calls.
     */
    public function __call(string $method, array $parameters): mixed
    {
        if (static::hasMacro($method)) {
            return $this->macroCall($method, $parameters);
        }

        if (! $this->class) {
            throw new BadMethodCallException('Cannot call state methods on a factory without a using class.');
        }

        if (! method_exists($this->class, $stateMethod = $this->getStateMethod($method))) {
            throw new BadMethodCallException("Method [{$method}] does not exist on [{$this->class}].");
        }

        if (! is_callable([$this->class, $stateMethod])) {
            throw new BadMethodCallException("Method [{$method}] is not callable on [{$this->class}].");
        }

        return $this->state(
            call_user_func([$this->class, $stateMethod], $parameters)
        );
    }

    /**
     * Get the state method name for the given method name.
     */
    protected function getStateMethod(string $method): string
    {
        return 'get'.ucfirst($method).'State';
    }
}
